.TH "shared_strings_callback_data" 3 "XLSX I/O" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shared_strings_callback_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "XML_Parser \fBxmlparser\fP"
.br
.ti -1c
.RI "struct \fBsharedstringlist\fP * \fBsharedstrings\fP"
.br
.ti -1c
.RI "int \fBinsst\fP"
.br
.ti -1c
.RI "int \fBinsi\fP"
.br
.ti -1c
.RI "int \fBintext\fP"
.br
.ti -1c
.RI "XML_Char * \fBtext\fP"
.br
.ti -1c
.RI "size_t \fBtextlen\fP"
.br
.ti -1c
.RI "XML_Char * \fBskiptag\fP"
.br
.ti -1c
.RI "size_t \fBskiptagcount\fP"
.br
.ti -1c
.RI "XML_StartElementHandler \fBskip_start\fP"
.br
.ti -1c
.RI "XML_EndElementHandler \fBskip_end\fP"
.br
.ti -1c
.RI "XML_CharacterDataHandler \fBskip_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XLSX I/O from the source code\&.
